version: '3.8'

services:
  web:
    image: php:8.2-apache
    container_name: php-web
    volumes:
      - ./src:/var/www/html
      - ./uploads:/var/www/html/uploads
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: jeuxvideo
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: adminpass
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  db-data:
