version: '3.8'

services:
  web:
    image: php:8.3-apache
    container_name: php-web
    volumes:
      - ./src:/var/www/html
      - ./uploads:/var/www/html/uploads
    ports:
      - "8000:80"
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: jeuxvideo
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
      PGUSER: test
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: adminpass
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "5050:80"
    volumes:
      - ./data/servers.json:/pgadmin4/servers.json
    depends_on:
      - db
